language: node_js
node_js: 
  - '8'
  - '9'
  - '10'
script: 
  - npm run build
deploy: 
  - provider: npm
    email: ackeedevelopment@gmail.com
    skip_cleanup: true
    api_key:
      secure: v1xlE0eNQmqhc4PSyQBKP//YTmwyjHwhX/2DugGbEP0ksWo8qyMeDUFFQQ4wYvkVJzlFG13DM+mZMFk/L3cgTmiG3a47Cn1eqq0ildaYvWptS8SlOQ069wm+3p/taSMADpnKHQad7ZHaHqGMFwJA4UuFjWQTn5zflQW8gT4MYwh7qf5tPwRMDjVckIPCSk/OF+BYWGpbtzqdHtklqre1LHZfLMNweNbPM3uQNZXs4+9TTAfMU5QppXrk3Bd44ElGHnl0+7Ik0jIbyJacaa4pEm+gAUEIL170X7Xh2RvEP+0lG8DKj1gTmsSl2BjpGF6QqRDiGXMaFgbbqI+9hn+J2G/CDX2OQtfV4ivXGeyxNnEMp6y3/IIIwJ+nIIPdi0NaxQ8M+wfFOwPrSTrkQsSiyLIa53I/OMnrec22q3SKQjjmIvmlPPFpgIYrgiFhhwPJFT1WR6vGX3PS3IBj5y1KqUvhyjUbzXpBRU9enqOu2mVLMqEFBGXcT0TH4UwfVa+8qxANn5DQBEe+0LVFHTML5UKoIRriQydg06G9ts/5HgOtUgDwUl8ftexl5dmmU4Y7jDjkgxf0mSWvMSwVnokJ+LKw3yEnVBr8H/fDMAs83bLCSwi++xuYIh2BIMj/s838qvVWackQTObTN3rDC1W/JsvKGID+4TPwe08HdQp/B0c=
    on:
      tags: true
      repo: AckeeCZ/fuqu